include: package:effective_dart/analysis_options.yaml
analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

linter:
  rules:
    lines_longer_than_80_chars: false
    prefer_const_constructors: true
    public_member_api_docs: false
    type_annotate_public_apis: false