name: glina_soundboard
description: Glina Soundboard &lt;3
version: 1.2.6+1.2.6

environment:
  sdk: '>=2.3.0-dev.0.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  soundpool: ^0.5.1
  shake: ^0.1.0
  path_provider: ^0.5.0+1
  auto_size_text: ^1.1.2
  shared_preferences: ^0.5.2
  flutter_slidable: ^0.4.9
  http: ^0.12.0+2
  material_design_icons_flutter: 3.2.3595
  flutter_web: any
  flutter_web_ui: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.4.0
  build_web_compilers: ^2.0.0
  pedantic: ^1.0.0

dependency_overrides:
  flutter_web:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web
  flutter_web_ui:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web_ui

flutter:
  uses-material-design: true
  assets:
    - zasoby/zdjecia/icon.png
    - zasoby/zdjecia/morze.jpg
    - zasoby/zdjecia/siedzacy.jpg
    - zasoby/audio/przyciski/AAAAA_kurwa.mp3
    - zasoby/audio/przyciski/lalloueciak_napleciak.mp3
    - zasoby/audio/przyciski/strasznie_glupio.mp3
    - zasoby/audio/major.mp3
    - zasoby/audio/przyciski/jek.mp3
    - zasoby/audio/AAAARRRR.mp3
    - zasoby/audio/przyciski/ahh_jest.mp3
    - zasoby/audio/przyciski/jebaniutki.mp3
    - zasoby/audio/przyciski/wooolny_jestem.mp3
    - zasoby/audio/przyciski/AAA_szkoda.mp3
    - zasoby/audio/przyciski/ajj_nieprzyjemnie.mp3
    - zasoby/audio/przyciski/famas.mp3
    - zasoby/audio/przyciski/famas_2.mp3
    - zasoby/audio/przyciski/niee.mp3
    - zasoby/audio/przyciski/nie_bawie_sie_tak.mp3
    - zasoby/audio/przyciski/kormoran.mp3
    - zasoby/audio/przyciski/tak_jest.mp3
    - zasoby/audio/przyciski/here_we_go.mp3
    - zasoby/audio/przyciski/soczysta_bula.mp3
    - zasoby/audio/przyciski/pierwsza_runda.mp3
    - zasoby/audio/przyciski/ale_dostalem_bule.mp3
    - zasoby/audio/przyciski/karniak_w_stopke.mp3
    - zasoby/audio/przyciski/glupio_agresywnie.mp3
    - zasoby/audio/przyciski/ale_zepsulem.mp3
    - zasoby/audio/przyciski/big_time_frags.mp3
    - zasoby/audio/przyciski/danke.mp3
    - zasoby/audio/przyciski/dmg.mp3
    - zasoby/audio/przyciski/raszing.mp3