name: glina_soundboard
description: Glina Soundboard
version: 1.3.7+1.3.7

environment:
  sdk: '>=2.3.0-dev.0.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  shake: ^0.1.0
  path_provider: ^0.5.0+1
  auto_size_text: ^1.1.2
  shared_preferences: ^0.5.2
  flutter_slidable: ^0.4.9
  http: ^0.12.0+2
  material_design_icons_flutter: 3.2.3595
  page_transition: ^1.1.0
  audioplayers: ^0.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  effective_dart: ^1.2.4


flutter:
  uses-material-design: true
  assets:
    - assets/audio/
    - assets/zdjecia/