version: 2
jobs:
  build:
    docker:
      - image: cirrusci/flutter
    working_directory: ~/glina_soundboard
    steps:
      - checkout
      - run:
          name: Flutter doctor
          command: flutter doctor
      #- run: flutter test
      - run:
          name: Decipher the files
          command: |
            echo $KEY_JKS | base64 --decode > android/app/key.jks
            echo $KEY_PROPERTIES | base64 --decode > android/key.properties

      - run:
          name: Flutter release build
          command: flutter build apk
      - run:
          name: Install PIP
          command: |
            sudo curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
            sudo python get-pip.py
      - run:
          name: Install awscli
          command: sudo pip install awscli
      - run:
          name: Deploy to S3
          command: aws s3 sync build/app/outputs/apk/release/ s3://glina-soundboard/ --delete --exclude "output.json"