version: 2
jobs:
  build:
    docker:
      - image: cirrusci/flutter
    working_directory: ~/glina_soundboard
    steps:
      - checkout
      - run: flutter doctor
      #- run: flutter test
      - run: flutter build apk
      - run: find . -name 'app-release.apk'
  deploy:
    docker:
      - image: cirrusci/flutter
    working_directory: ~/glina_soundboard
    steps:
      - run:
          name: Install PIP
          command: |
            sudo curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
            sudo python get-pip.py
            ls -al
      - run:
          name: Install awscli
          command: sudo pip install awscli
      - run:
          name: Deploy to S3
          command: |
            ls -al
            find . -name 'app-release.apk'
            aws s3 sync build/app/outputs/apk/release/app-release.apk s3://glina-soundboard/ --delete
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master